before_cache:
- sudo rm -rf $HOME/.m2/repository/com/yahoo/vespa
- sudo rm -rf $HOME/.m2/repository/repository.xml
- du --summarize --human-readable $HOME/.m2/repository
- du --summarize --human-readable $HOME/.ccache
- cp /tmp/classpathFile $HOME/CACHE/classpathFile
before_install:
- if [ "$TRAVIS_OS_NAME" == "osx" ];        then sed -i '' 's/<gib.enabled>true/<gib.enabled>false/'
  $TRAVIS_BUILD_DIR/pom.xml;        else sed -i 's/<gib.enabled>true/<gib.enabled>false/'
  $TRAVIS_BUILD_DIR/pom.xml;        fi
before_script:
- if [ "$TRAVIS_OS_NAME" == "osx" ];    then sed -i '' 's/<gib.enabled>false/<gib.enabled>true/'
  $TRAVIS_BUILD_DIR/pom.xml;    else sed -i 's/<gib.enabled>false/<gib.enabled>true/'
  $TRAVIS_BUILD_DIR/pom.xml;    fi
- if [[ -e $HOME/CACHE/classpathFile ]]; then cp $HOME/CACHE/classpathFile /tmp/;
  fi
branches:
  only:
  - master
cache:
  directories:
  - $HOME/.m2
  - $HOME/.ccache
  timeout: 900
install: true
language: minimal
script:
- touch /tmp/NOW
- echo GIBSTUDYSTART $(date)
- ./travis/travis.sh
- echo GIBSTUDYEND $(date)
- cd $TRAVIS_BUILD_DIR
- echo TESTNUM $(find . -name TEST-*.xml -newer /tmp/NOW | wc -l)
services:
- docker
sudo: required
